export * from './checkDeviceOS'
export * from './getSlideImage'
export * from './getStarsImage'
export * from './goToTopPage'
export * from './setValueInClipboard'
export * from './showConnectionRestoredAlert'
export * from './showLossOfConnectionAlert'
