export enum PATHS {
  APP_STORE = 'https://apps.apple.com/us/app/ai-arta-art-photo-generator/id1642969698',
  GOGGLE_PLAY = 'https://play.google.com/store/apps/details?id=ai.generated.art.maker.image.picture.photo.generator.painting',
  FACEBOOK = 'https://www.facebook.com/aiartapp',
  TIKTOK = 'https://www.tiktok.com/@arta_app',
  INSTAGRAM = 'https://www.instagram.com/aiart_app/',
  DISCORD = 'https://discord.com/invite/a5MXGUqeBc',
  PRIVACY_POLICY = 'https://aiby.mobi/ai_art_ios/privacy/en/',
  ANDROID_REVIEW = 'https://play.google.com/store/apps/details?id=ai.generated.art.maker.image.picture.photo.generator.painting',
  IOS_REVIEW = 'https://apps.apple.com/us/app/ai-arta-art-photo-generator/id1642969698',
}

export const array = [
  {
    timestamp: 1,
    user_id: "user_id1",
    user_type: "user_type1",
    service: "service1",
    request_id: "request_id1",
    image_url: "image_url1",
    prompt: "prompt1",
    original_prompt: "original_prompt1",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/unlimited user/df6330af143f4a6eb8ff660611610b94.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt1",
    original_negative_prompt: "original_negative_prompt",
  },
  {
    timestamp: 2,
    user_id: "user_id2",
    user_type: "user_type2",
    service: "service2",
    request_id: "request_id2",
    image_url: "image_url2",
    prompt: "prompt2 prompt2-2 prompt2-3 prompt2-4 prompt2 prompt2-2 prompt2-3 prompt2-4  prompt2 prompt2-2 prompt2-3 prompt2-4  prompt2 prompt2-2 prompt2-3 prompt2-4  prompt2 prompt2-2 prompt2-3 prompt2-4  prompt2 prompt2-2 prompt2-3 prompt2-4  prompt2 prompt2-2 prompt2-3 prompt2-4  prompt2 prompt2-2 prompt2-3 prompt2-4  prompt2 prompt2-2 prompt2-3 prompt2-4  prompt2 prompt2-2 prompt2-3 prompt2-4",
    original_prompt: "original_prompt2",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/unlimited user/63660bca661349dd96519eaba5337288.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt2",
    original_negative_prompt: "original_negative_prompt",
  },
  {
    timestamp: 3,
    user_id: "user_id3",
    user_type: "user_type3",
    service: "service3",
    request_id: "request_id3",
    image_url: "image_url3",
    prompt: "prompt3",
    original_prompt: "original_prompt3",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/unlimited user/df6330af143f4a6eb8ff660611610b94.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt3",
    original_negative_prompt: "original_negative_prompt",
  },
  {
    timestamp: 4,
    user_id: "user_id4",
    user_type: "user_type4",
    service: "service4",
    request_id: "request_id4",
    image_url: "image_url4",
    prompt: "prompt4",
    original_prompt: "original_prompt4",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/63ff62e1126785d3c570bc3f/5781c0fc06784509adbc565457f06b5f.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt4",
    original_negative_prompt: "original_negative_prompt",
  },
  {
    timestamp: 1,
    user_id: "user_id1",
    user_type: "user_type1",
    service: "service1",
    request_id: "request_id1",
    image_url: "image_url1",
    prompt: "prompt1",
    original_prompt: "original_prompt1",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/unlimited user/7827e43577f64c448d5a6ae212d77bfd.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt1",
    original_negative_prompt: "original_negative_prompt",
  },
  {
    timestamp: 2,
    user_id: "user_id2",
    user_type: "user_type2",
    service: "service2",
    request_id: "request_id2",
    image_url: "image_url2",
    prompt: "prompt2 prompt2-2 prompt2-3 prompt2-4",
    original_prompt: "original_prompt2",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/unlimited user/d1699ed1f3aa4682b53ff7238b7371fb.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt2",
    original_negative_prompt: "original_negative_prompt",
  },
  {
    timestamp: 3,
    user_id: "user_id3",
    user_type: "user_type3",
    service: "service3",
    request_id: "request_id3",
    image_url: "image_url3",
    prompt: "prompt3",
    original_prompt: "original_prompt3",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/unlimited user/eac96129e7a5445b91b4703b9e1f5d59.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt3",
    original_negative_prompt: "original_negative_prompt",
  },
  {
    timestamp: 4,
    user_id: "user_id4",
    user_type: "user_type4",
    service: "service4",
    request_id: "request_id4",
    image_url: "image_url4",
    prompt: "prompt4",
    original_prompt: "original_prompt4",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/unlim user/6fd700a6136a4d8f91c15c6ce91acbbe.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt4",
    original_negative_prompt: "original_negative_prompt",
  },
  {
    timestamp: 1,
    user_id: "user_id1",
    user_type: "user_type1",
    service: "service1",
    request_id: "request_id1",
    image_url: "image_url1",
    prompt: "prompt1",
    original_prompt: "original_prompt1",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/unlimited user/8add83f7d2aa403ab9c0dd659e984ef1.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt1",
    original_negative_prompt: "original_negative_prompt",
  },
  {
    timestamp: 2,
    user_id: "user_id2",
    user_type: "user_type2",
    service: "service2",
    request_id: "request_id2",
    image_url: "image_url2",
    prompt: "prompt2 prompt2-2 prompt2-3 prompt2-4",
    original_prompt: "original_prompt2",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/unlimited user/9ef48bfb43554bbc96ef7506d1ce8e09.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt2",
    original_negative_prompt: "original_negative_prompt",
  },
  {
    timestamp: 3,
    user_id: "user_id3",
    user_type: "user_type3",
    service: "service3",
    request_id: "request_id3",
    image_url: "image_url3",
    prompt: "prompt3",
    original_prompt: "original_prompt3",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/unlimited user/d511c7faf5d04596ade90ad348310304.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt3",
    original_negative_prompt: "original_negative_prompt",
  },
  {
    timestamp: 4,
    user_id: "user_id4",
    user_type: "user_type4",
    service: "service4",
    request_id: "request_id4",
    image_url: "image_url4",
    prompt: "prompt4",
    original_prompt: "original_prompt4",
    style: "style",
    model: "model",
    original_image_url: "https://aiart-images-dev.s3.dualstack.us-east-2.amazonaws.com/dreamstudio/6441219d3d39f606a56edfa9/a3cc1147cfd646018c4a08978a060a67.png",
    like_user: false,
    like_manager: false,
    like_count: 1,
    negative_prompt: "negative_prompt4",
    original_negative_prompt: "original_negative_prompt",
  },
]
